node { 
  // Pull code from GitLab
  stage('Git Checkout') { 
	checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: '3ed0fde6-cc83-4134-92d8-b31226cb79f3', url: 'git@192.168.0.110:devuser/tomcat-jenkins-demo.git']]])
  // This director could be use pipeline syntax to generate.
  }
  // Build container image and push to Harbor registry
  stage('Build and Push Image') {
	sh '''	
	REPOSITORY=harbor.domain12.example.com:8880/library/tomcat-jenkins-demo:v1.0.0
	sudo docker login -u admin -p redhat harbor.domain12.example.com:8880
	sudo docker build -t ${REPOSITORY} .
	sudo docker push ${REPOSITORY}
	'''
  }
  // Deploy container to docker host
  stage('Deploy to Podman') {
	sh '''
	REPOSITORY=harbor.domain12.example.com:8880/library/tomcat-jenkins-demo:v1.0.0
	sudo docker pull ${REPOSITORY}
	sudo docker run -d --name tomcat-java-demo -p 88:8080 ${REPOSITORY}
	'''
   }
}
